/*
Copyright Mobarak Hossain.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	crdcomv1 "github.com/MobarakHsn/CRD_Controller/pkg/apis/crd.com/v1"
	versioned "github.com/MobarakHsn/CRD_Controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/MobarakHsn/CRD_Controller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/MobarakHsn/CRD_Controller/pkg/client/listers/crd.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CustomInformer provides access to a shared informer and lister for
// Customs.
type CustomInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.CustomLister
}

type customInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCustomInformer constructs a new informer for Custom type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCustomInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCustomInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCustomInformer constructs a new informer for Custom type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCustomInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1().Customs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1().Customs(namespace).Watch(context.TODO(), options)
			},
		},
		&crdcomv1.Custom{},
		resyncPeriod,
		indexers,
	)
}

func (f *customInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCustomInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *customInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&crdcomv1.Custom{}, f.defaultInformer)
}

func (f *customInformer) Lister() v1.CustomLister {
	return v1.NewCustomLister(f.Informer().GetIndexer())
}
