/*
Copyright Mobarak Hossain.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/MobarakHsn/CRD_Controller/pkg/apis/crd.com/v1"
	crdcomv1 "github.com/MobarakHsn/CRD_Controller/pkg/client/applyconfiguration/crd.com/v1"
	scheme "github.com/MobarakHsn/CRD_Controller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CustomsGetter has a method to return a CustomInterface.
// A group's client should implement this interface.
type CustomsGetter interface {
	Customs(namespace string) CustomInterface
}

// CustomInterface has methods to work with Custom resources.
type CustomInterface interface {
	Create(ctx context.Context, custom *v1.Custom, opts metav1.CreateOptions) (*v1.Custom, error)
	Update(ctx context.Context, custom *v1.Custom, opts metav1.UpdateOptions) (*v1.Custom, error)
	UpdateStatus(ctx context.Context, custom *v1.Custom, opts metav1.UpdateOptions) (*v1.Custom, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Custom, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.CustomList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Custom, err error)
	Apply(ctx context.Context, custom *crdcomv1.CustomApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Custom, err error)
	ApplyStatus(ctx context.Context, custom *crdcomv1.CustomApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Custom, err error)
	CustomExpansion
}

// customs implements CustomInterface
type customs struct {
	client rest.Interface
	ns     string
}

// newCustoms returns a Customs
func newCustoms(c *CrdV1Client, namespace string) *customs {
	return &customs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the custom, and returns the corresponding custom object, and an error if there is any.
func (c *customs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Custom, err error) {
	result = &v1.Custom{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("customs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Customs that match those selectors.
func (c *customs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.CustomList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.CustomList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("customs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested customs.
func (c *customs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("customs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a custom and creates it.  Returns the server's representation of the custom, and an error, if there is any.
func (c *customs) Create(ctx context.Context, custom *v1.Custom, opts metav1.CreateOptions) (result *v1.Custom, err error) {
	result = &v1.Custom{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("customs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(custom).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a custom and updates it. Returns the server's representation of the custom, and an error, if there is any.
func (c *customs) Update(ctx context.Context, custom *v1.Custom, opts metav1.UpdateOptions) (result *v1.Custom, err error) {
	result = &v1.Custom{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("customs").
		Name(custom.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(custom).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *customs) UpdateStatus(ctx context.Context, custom *v1.Custom, opts metav1.UpdateOptions) (result *v1.Custom, err error) {
	result = &v1.Custom{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("customs").
		Name(custom.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(custom).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the custom and deletes it. Returns an error if one occurs.
func (c *customs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("customs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *customs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("customs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched custom.
func (c *customs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Custom, err error) {
	result = &v1.Custom{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("customs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied custom.
func (c *customs) Apply(ctx context.Context, custom *crdcomv1.CustomApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Custom, err error) {
	if custom == nil {
		return nil, fmt.Errorf("custom provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(custom)
	if err != nil {
		return nil, err
	}
	name := custom.Name
	if name == nil {
		return nil, fmt.Errorf("custom.Name must be provided to Apply")
	}
	result = &v1.Custom{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("customs").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *customs) ApplyStatus(ctx context.Context, custom *crdcomv1.CustomApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Custom, err error) {
	if custom == nil {
		return nil, fmt.Errorf("custom provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(custom)
	if err != nil {
		return nil, err
	}

	name := custom.Name
	if name == nil {
		return nil, fmt.Errorf("custom.Name must be provided to Apply")
	}

	result = &v1.Custom{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("customs").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
